"""initial schema

Revision ID: 8976c65629fc
Revises:
Create Date: 2026-04-20 22:38:41.882664

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "8976c65629fc"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("exercise_muscles_muscle_id_fkey"), "exercise_muscles", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "exercise_muscles", "muscles", ["muscle_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint(
        op.f("workout_exercises_exercise_id_fkey"),
        "workout_exercises",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("workout_exercises_workout_id_fkey"),
        "workout_exercises",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "workout_exercises",
        "workouts",
        ["workout_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "workout_exercises",
        "exercises",
        ["exercise_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "workout_exercises", type_="foreignkey")
    op.drop_constraint(None, "workout_exercises", type_="foreignkey")
    op.create_foreign_key(
        op.f("workout_exercises_workout_id_fkey"),
        "workout_exercises",
        "workouts",
        ["workout_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("workout_exercises_exercise_id_fkey"),
        "workout_exercises",
        "exercises",
        ["exercise_id"],
        ["id"],
    )
    op.drop_constraint(None, "exercise_muscles", type_="foreignkey")
    op.create_foreign_key(
        op.f("exercise_muscles_muscle_id_fkey"),
        "exercise_muscles",
        "muscles",
        ["muscle_id"],
        ["id"],
    )
    # ### end Alembic commands ###
